### Imports & Paths

In [1]:
import pandas as pd
import numpy as np
import json
from pathlib import Path

### Load PolitiFact Dataset

In [2]:
print("Loading PolitiFact Dataset")

politifact_path = Path('/Users/satwik/Documents/GitHub/UF-EEE6778-Fall25-TermProject/data/raw/politifact_factcheck_data.json')

politifact_data = []
try:
    with open(politifact_path, "r") as f:
        politifact_data = json.load(f)
except json.JSONDecodeError:
    print("Loading as JSONL format (one JSON object per line)...")
    with open(politifact_path, "r") as f:
        for line in f:
            line = line.strip()
            if line:
                politifact_data.append(json.loads(line))

df_politifact = pd.DataFrame(politifact_data)
print(f"PolitiFact Dataset loaded: {df_politifact.shape}")
df_politifact.head(20)

Loading PolitiFact Dataset
Loading as JSONL format (one JSON object per line)...
PolitiFact Dataset loaded: (21152, 8)

,verdict,statement_originator,statement,statement_date,statement_source,factchecker,factcheck_date,factcheck_analysis_link
0,true,Barack Obama,John McCain opposed bankruptcy protections for...,6/11/2008,speech,Adriel Bettelheim,6/16/2008,https://www.politifact.com/factchecks/2008/jun...
1,false,Matt Gaetz,"""Bennie Thompson actively cheer-led riots in t...",6/7/2022,television,Yacob Reyes,6/13/2022,https://www.politifact.com/factchecks/2022/jun...
2,mostly-true,Kelly Ayotte,"Says Maggie Hassan was ""out of state on 30 day...",5/18/2016,news,Clay Wirestone,5/27/2016,https://www.politifact.com/factchecks/2016/may...
3,false,Bloggers,"""BUSTED: CDC Inflated COVID Numbers, Accused o...",2/1/2021,blog,Madison Czopek,2/5/2021,https://www.politifact.com/factchecks/2021/feb...
4,half-true,Bobby Jindal,"""I'm the only (Republican) candidate that has ...",8/30/2015,television,Linda Qiu,8/30/2015,https://www.politifact.com/factchecks/2015/aug...
5,true,S.E. Cupp,"""There are actually only 30 countries that pra...",8/23/2015,news,Will Cabaniss,8/23/2015,https://www.politifact.com/factchecks/2015/aug...
6,false,Michele Bachmann,"""My husband and I have never gotten a penny of...",6/26/2011,news,Robert Farley,7/1/2011,https://www.politifact.com/factchecks/2011/jul...
7,true,George Turner,"""If you go strictly by the numbers, crime is d...",4/4/2011,news,Willoughby Mariano,4/18/2011,https://www.politifact.com/factchecks/2011/apr...
8,mostly-true,Kent Conrad,"""The American people say, don't touch Social S...",1/23/2011,other,Angie Drobnic Holan,1/27/2011,https://www.politifact.com/factchecks/2011/jan...
9,true,Mandela Barnes,"""Since 1978, CEO compensation rose over 1,000%...",5/23/2021,social_media,Madeline Heim,6/2/2021,https://www.politifact.com/factchecks/2021/jun...
10,pants-fire,Chris Telfer,"Says her accomplishments include ""a fiscally r...",3/6/2012,news,Janie Har,3/14/2012,https://www.politifact.com/factchecks/2012/mar...
11,false,Carlos Beruff,"Says President Obama’s deal ""allows Iran to pr...",5/5/2016,news,Joshua Gillin,5/11/2016,https://www.politifact.com/factchecks/2016/may...
12,mostly-true,Hillary Clinton,"Says ""Donald Trump says climate change is a ho...",6/2/2016,speech,Louis Jacobson,6/3/2016,https://www.politifact.com/factchecks/2016/jun...
13,false,Sidney Powell,"""At least 450,000 ballots in the key states .....",11/8/2020,news,Samantha Putterman,11/20/2020,https://www.politifact.com/factchecks/2020/nov...
14,mostly-true,Stephen Carter,"""More than 70 percent of American adults have ...",12/4/2014,news,Jon Greenberg,12/8/2014,https://www.politifact.com/factchecks/2014/dec...
15,pants-fire,Americans for Prosperity,Says the stimulus bill sent tax credits overse...,4/26/2012,advertisement,Becky Bowers,5/2/2012,https://www.politifact.com/factchecks/2012/may...
16,mostly-false,Bob Buckhorn,"Tampa Bay is ""leading the state in jobs creati...",1/15/2015,campaign,Richard Danielson,1/15/2015,https://www.politifact.com/factchecks/2015/jan...
17,mostly-false,Kelly Loeffler,"Says Raphael Warnock has ""said we need to open...",12/9/2020,news,Tom Kertscher,12/18/2020,https://www.politifact.com/factchecks/2020/dec...
18,pants-fire,Michele Bachmann,"The IRS is going to be ""in charge"" of ""a huge ...",5/15/2013,news,Louis Jacobson,5/20/2013,https://www.politifact.com/factchecks/2013/may...
19,false,The Gateway Pundit,"""Newly discovered video shows late night deliv...",2/5/2021,news,Clara Hendrickson,2/5/2021,https://www.politifact.com/factchecks/2021/feb...

### Load Snopes Dataset

In [3]:
print("Loading Snopes Dataset")

snopes_path = Path('/Users/satwik/Documents/GitHub/UF-EEE6778-Fall25-TermProject/data/raw/snopeswithsum.csv')
df_snopes = pd.read_csv(snopes_path)

print(f"Snopes Dataset loaded: {df_snopes.shape}")
df_snopes.head(20)

Loading Snopes Dataset
Snopes Dataset loaded: (4550, 9)

,question,comment,claim,rate,what's true,what's false,what's unknown,origin,summary
0,Did Kamala Harris Support Abortion Until the T...,The Democratic vice-presidential candidate's p...,"U.S. Sen. Kamala Harris, D-Calif., supports th...",Mixture,"U.S. Sen. Kamala Harris, D-Calif, has maintain...",She has not explicitly stated that she support...,NaN,Debates surrounding abortion frequently resurf...,"U.S. Sen. Kamala Harris, D-Calif., has been to..."
1,Did Hitler Invent the Inflatable Sex Doll?,Nothing attracts curiosity like a lurid combin...,Adolf Hitler was behind the invention of the f...,False,NaN,NaN,NaN,"In late July 2020, readers shared a 2016 blog ...",Readers shared a 2016 blog post with the headl...
2,Does Texting ‘RBG’ to 50409 Send a Letter to Y...,The automated political advocacy service Resis...,"Texting ""RBG"" to 50409 engages a service calle...",True,NaN,NaN,NaN,"In September 2020, following the death of U.S....",Readers asked Snopes to examine the accuracy a...
3,Pride Parade Fire Hydrant Mishap,An image depicts a man stabbed at an altercati...,An image depicts an overenthusiastic Pride att...,Miscaptioned,NaN,NaN,NaN,Yearly Pride festivities were marked on 26 Jun...,A Twitter user tweeted a photograph of a blood...
4,Swedish Police Hand Out ‘Don’t Touch Me’ Brace...,Police in Sweden have introduced sexual assaul...,Swedish police have introduced anti-sexual ass...,Mixture,Police in Sweden are distributing colored brac...,Swedish police did not create or distribute th...,NaN,"On 30 June 2016, the Federalist Papers web sit...",Police in Sweden have come up with a sure-fire...
5,Did Trump Say He Might Sign an Exec Order Barr...,"""Was he joking?"" has become a frequent questio...","In September 2020, U.S. President Donald Trump...",Mixture,"On Sept. 19, 2020, Trump said at a rally in No...",NaN,It's unclear whether Trump was joking.,"In September 2020, readers asked Snopes to exa...","In September 2020, readers asked Snopes to exa..."
6,Did the White House Watch the Benghazi Attack ...,Claims that top Obama administration officials...,Top Obama administration officials watched the...,False,NaN,NaN,NaN,One of the more common fault-finding rumors as...,Forbes published an opinion piece claiming tha...
7,Do Color Codes on Toothpaste Tubes Identify Th...,The colored squares on toothpaste tubes suppos...,The colored squares on toothpaste tubes identi...,False,NaN,NaN,NaN,A popular item about markings on toothpaste tu...,The colored squares or rectangular bars found ...
8,Did the Last Surviving WWII Veteran March Alon...,"A photograph of the ""last surviving veteran"" o...",A photograph depicts last surviving veteran of...,Miscaptioned,The photograph depicts an elderly gentleman cr...,The man wasn't identified as the last survivin...,NaN,A number of social media pages devoted to attr...,A photo of a crying older gentleman marching a...
9,Did Ruth Bader Ginsburg Say that Pedophilia Wa...,A 1974 report co-authored by Ruth Bader Ginsbu...,Ruth Bader Ginsburg said that pedophilia was g...,False,NaN,NaN,NaN,The language in a 1974 report that was co-auth...,Ruth Bader Ginsburg was accused of wanting to ...
10,Bow Hunting Wild Horses,A photograph showing a man posing with a wild ...,A photograph shows a man posing with a horse h...,True,NaN,NaN,NaN,"In June 2016, a photograph purportedly showing...",The New South Wales government announced a pla...
11,‘Welcome to Mingo County’,A fake photograph shows a 'Welcome Sign' outsi...,A photograph shows a 'Welcome Sign' outside of...,False,NaN,NaN,NaN,A photograph purportedly showing a “Welcome Si...,A photograph purportedly showing a “Welcome Si...
12,Dwayne Johnson Arrested,"Actor Dwayne (""The Rock"") Johnson has not been...",Dwayne Johnson was arrested for illegally impo...,False,NaN,NaN,NaN,"On 4 July 2016, multiple Twitter and Facebook ...","On 4 July 2016, multiple Twitter and Facebook ..."
13,‘Guccifer’ Is Not Missing or Dead,"Hacker Marcel Lazăr Lehel, also known as ""Gucc...",Hacker Guccifer (Marcel Lazăr Lehel) is missin...,False,NaN,NaN,NaN,"On 2 July 2016, Hillary Clinton was interviewe...",The Russian Foreign Intelligence Service (SVR)...
14,Fireworks Explode in Woman During Shoplifting ...,A hoax news article reported that a woman was ...,A woman was injured while trying to steal fire...,False,NaN,NaN,NaN,"On 5 July 2016, the web site News10Live publis...",A Philadelphia woman has been hospitalized and...
15,‘Pawn Stars’ Personality Richard Harrison Dies...,After years of being targeted by celebrity dea...,"Richard Harrison, known as the ""the Old Man"" o...",True,NaN,NaN,NaN,"LAS VEGAS (AP) — “Pawn Stars” patriarch, Richa...","""Pawn Stars"" patriarch Richard Benjamin Harris..."
16,Tim Hortons Adding Marijuana to Their Menu,A hoax news article reported that Canadian res...,Tim Hortons will add marijuana to its menu in ...,False,NaN,NaN,NaN,"On 1 July 2016, the entertainment web site The...","Canada is moving to legalize pot in 2017, but ..."
17,Obama to Remove Statue of Liberty Because It O...,Reports that President Obama is dismantling th...,President Obama plans to remove the Statue of ...,False,NaN,NaN,NaN,"On 5 July 2016, the web site Southern Conserva...",Southern Conservative Daily falsely reported t...
18,"At 191 Years Old, Mama Esifiho May be Oldest W...","According to unsubstantiated reports, the olde...",A 191-year-old woman named Mama Esifiho lives ...,Unproven,NaN,NaN,NaN,Photographs purportedly showing a 191-year-old...,Photographs purportedly showing a 191-year-old...
19,Cop Shoots 2-Year-Old Black Baby After Mistaki...,A 2015 fake news item claiming a Baltimore off...,A Baltimore police officer shot and killed two...,False,NaN,NaN,NaN,"In June 2015, multiple fake news web sites pub...",Two-year-old Malik Gibson was shot by Baltimor...

### Preprocess and Standardize Columns

In [4]:
# Politifact Preprocessing & Standardization
df_politifact = df_politifact.rename(columns={
    "statement": "claim_text",
    "verdict": "verdict_original",
    "statement_originator": "originator",
    "factcheck_analysis_link": "url"
})
df_politifact["dataset_source"] = "PolitiFact"
df_politifact["summary"] = None
df_politifact["claim_id"] = [f"P{i:05d}" for i in range(1, len(df_politifact)+1)]

mapping_pf = {
    "true": "Likely True",
    "mostly-true": "Likely True",
    "half-true": "Uncertain",
    "mostly-false": "Likely False",
    "false": "Likely False",
    "pants-fire": "Likely False"
}
df_politifact["verdict_mapped"] = df_politifact["verdict_original"].str.lower().map(mapping_pf)

df_politifact = df_politifact[
    ["claim_id", "claim_text", "verdict_original", "verdict_mapped",
     "summary", "originator", "url", "dataset_source"]
]

# Snopes Preprocessing & Standardization
df_snopes = df_snopes.rename(columns={
    "claim": "claim_text",
    "rate": "verdict_original",
    "summary": "summary"
})
df_snopes["originator"] = None
df_snopes["url"] = None
df_snopes["dataset_source"] = "Snopes"
df_snopes["claim_id"] = [f"S{i:05d}" for i in range(1, len(df_snopes)+1)]

mapping_snopes = {
    "true": "Likely True",
    "mostly true": "Likely True",
    "false": "Likely False",
    "mostly false": "Likely False",
    "mixture": "Uncertain",
    "unproven": "Uncertain",
    "miscaptioned": "Uncertain",
    "legend": "Uncertain",
    "outdated": "Uncertain",
    "scam": "Likely False",
    "satire": "Uncertain",
    "research in progress": "Uncertain",
    "correct attribution": "Likely True",
    "misattributed": "Likely False"
}
df_snopes["verdict_mapped"] = df_snopes["verdict_original"].str.lower().map(mapping_snopes)

df_snopes = df_snopes[
    ["claim_id", "claim_text", "verdict_original", "verdict_mapped",
     "summary", "originator", "url", "dataset_source"]
]

### Merge and Save Unified Dataset

In [5]:
# Merge both datasets
df_merged = pd.concat([df_politifact, df_snopes], ignore_index=True)
print(f"Merged dataset shape: {df_merged.shape}")

# Check summary
print("\nNull value summary:")
print(df_merged.isnull().sum())

print("\nVerdict Distribution:")
print(df_merged['verdict_mapped'].value_counts(dropna=False))

# Save
output_path = Path('/Users/satwik/Documents/GitHub/UF-EEE6778-Fall25-TermProject/data/processed/merged_factcheck_dataset.csv')
output_path.parent.mkdir(parents=True, exist_ok=True)
df_merged.to_csv(output_path, index=False)
print(f"\n Unified dataset saved to:\n{output_path}")

Merged dataset shape: (25702, 8)

Null value summary:
claim_id                0
claim_text              0
verdict_original        0
verdict_mapped        162
summary             21152
originator           4550
url                  4550
dataset_source          0
dtype: int64

Verdict Distribution:
verdict_mapped
Likely False    14390
Likely True      6526
Uncertain        4624
NaN               162
Name: count, dtype: int64

 Unified dataset saved to:
/Users/satwik/Documents/GitHub/UF-EEE6778-Fall25-TermProject/data/processed/merged_factcheck_dataset.csv

In [6]:
#Display of Merged Dataset
df_merged.head(50)

,claim_id,claim_text,verdict_original,verdict_mapped,summary,originator,url,dataset_source
0,P00001,John McCain opposed bankruptcy protections for...,true,Likely True,None,Barack Obama,https://www.politifact.com/factchecks/2008/jun...,PolitiFact
1,P00002,"""Bennie Thompson actively cheer-led riots in t...",false,Likely False,None,Matt Gaetz,https://www.politifact.com/factchecks/2022/jun...,PolitiFact
2,P00003,"Says Maggie Hassan was ""out of state on 30 day...",mostly-true,Likely True,None,Kelly Ayotte,https://www.politifact.com/factchecks/2016/may...,PolitiFact
3,P00004,"""BUSTED: CDC Inflated COVID Numbers, Accused o...",false,Likely False,None,Bloggers,https://www.politifact.com/factchecks/2021/feb...,PolitiFact
4,P00005,"""I'm the only (Republican) candidate that has ...",half-true,Uncertain,None,Bobby Jindal,https://www.politifact.com/factchecks/2015/aug...,PolitiFact
5,P00006,"""There are actually only 30 countries that pra...",true,Likely True,None,S.E. Cupp,https://www.politifact.com/factchecks/2015/aug...,PolitiFact
6,P00007,"""My husband and I have never gotten a penny of...",false,Likely False,None,Michele Bachmann,https://www.politifact.com/factchecks/2011/jul...,PolitiFact
7,P00008,"""If you go strictly by the numbers, crime is d...",true,Likely True,None,George Turner,https://www.politifact.com/factchecks/2011/apr...,PolitiFact
8,P00009,"""The American people say, don't touch Social S...",mostly-true,Likely True,None,Kent Conrad,https://www.politifact.com/factchecks/2011/jan...,PolitiFact
9,P00010,"""Since 1978, CEO compensation rose over 1,000%...",true,Likely True,None,Mandela Barnes,https://www.politifact.com/factchecks/2021/jun...,PolitiFact
10,P00011,"Says her accomplishments include ""a fiscally r...",pants-fire,Likely False,None,Chris Telfer,https://www.politifact.com/factchecks/2012/mar...,PolitiFact
11,P00012,"Says President Obama’s deal ""allows Iran to pr...",false,Likely False,None,Carlos Beruff,https://www.politifact.com/factchecks/2016/may...,PolitiFact
12,P00013,"Says ""Donald Trump says climate change is a ho...",mostly-true,Likely True,None,Hillary Clinton,https://www.politifact.com/factchecks/2016/jun...,PolitiFact
13,P00014,"""At least 450,000 ballots in the key states .....",false,Likely False,None,Sidney Powell,https://www.politifact.com/factchecks/2020/nov...,PolitiFact
14,P00015,"""More than 70 percent of American adults have ...",mostly-true,Likely True,None,Stephen Carter,https://www.politifact.com/factchecks/2014/dec...,PolitiFact
15,P00016,Says the stimulus bill sent tax credits overse...,pants-fire,Likely False,None,Americans for Prosperity,https://www.politifact.com/factchecks/2012/may...,PolitiFact
16,P00017,"Tampa Bay is ""leading the state in jobs creati...",mostly-false,Likely False,None,Bob Buckhorn,https://www.politifact.com/factchecks/2015/jan...,PolitiFact
17,P00018,"Says Raphael Warnock has ""said we need to open...",mostly-false,Likely False,None,Kelly Loeffler,https://www.politifact.com/factchecks/2020/dec...,PolitiFact
18,P00019,"The IRS is going to be ""in charge"" of ""a huge ...",pants-fire,Likely False,None,Michele Bachmann,https://www.politifact.com/factchecks/2013/may...,PolitiFact
19,P00020,"""Newly discovered video shows late night deliv...",false,Likely False,None,The Gateway Pundit,https://www.politifact.com/factchecks/2021/feb...,PolitiFact
20,P00021,"Says Donald Trump ""literally has no plans to m...",mostly-true,Likely True,None,Roberta Lange,https://www.politifact.com/factchecks/2016/jun...,PolitiFact
21,P00022,"Post says a recent bill passed, and ""We get an...",pants-fire,Likely False,None,Facebook posts,https://www.politifact.com/factchecks/2021/jul...,PolitiFact
22,P00023,"With voting by mail, ""you get thousands and th...",false,Likely False,None,Donald Trump,https://www.politifact.com/factchecks/2020/apr...,PolitiFact
23,P00024,"During his governorship, Virginia made ""the la...",mostly-false,Likely False,None,Terry McAuliffe,https://www.politifact.com/factchecks/2019/mar...,PolitiFact
24,P00025,"""In the entire public school system in Camden ...",mostly-true,Likely True,None,Chris Christie,https://www.politifact.com/factchecks/2014/jan...,PolitiFact
25,P00026,"Says he is ""cutting illegal immigration in half.""",false,Likely False,None,Donald Trump,https://www.politifact.com/factchecks/2019/oct...,PolitiFact
26,P00027,"""There is racism physically built into some of...",true,Likely True,None,Pete Buttigieg,https://www.politifact.com/factchecks/2021/apr...,PolitiFact
27,P00028,"Austin has ""over 1,000 city employees that mak...",mostly-true,Likely True,None,Jay Wiley,https://www.politifact.com/factchecks/2014/sep...,PolitiFact
28,P00029,"Says Marco Rubio ""has a 98 percent voting reco...",mostly-true,Likely True,None,Patrick Murphy,https://www.politifact.com/factchecks/2016/oct...,PolitiFact
29,P00030,"Says John Bolton ""fundamentally was a man of t...",pants-fire,Likely False,None,Tucker Carlson,https://www.politifact.com/factchecks/2019/sep...,PolitiFact
30,P00031,A German doctor discovered the COVID-19 vaccin...,false,Likely False,None,Facebook posts,https://www.politifact.com/factchecks/2022/jan...,PolitiFact
31,P00032,Says he lived in a colonia while working as a ...,false,Likely False,None,David Alameel,https://www.politifact.com/factchecks/2014/jul...,PolitiFact
32,P00033,"""The Republicans have demanded deep cuts in ed...",mostly-true,Likely True,None,Chris Van Hollen,https://www.politifact.com/factchecks/2011/apr...,PolitiFact
33,P00034,"""75% of Republicans have been vaccinated"" agai...",false,Likely False,None,Terri Bryant,https://www.politifact.com/factchecks/2021/oct...,PolitiFact
34,P00035,"""Creating 25 jobs in Umatilla County has the s...",mostly-true,Likely True,None,John Kitzhaber,https://www.politifact.com/factchecks/2011/jun...,PolitiFact
35,P00036,"""When I become the nominee, the Democratic nom...",mostly-true,Likely True,None,Kendrick Meek,https://www.politifact.com/factchecks/2010/jun...,PolitiFact
36,P00037,"Financial conflict-of-interest ""laws don't app...",true,Likely True,None,Rudy Giuliani,https://www.politifact.com/factchecks/2016/nov...,PolitiFact
37,P00038,"Says ""J.B. Pritzker’s tax plan"" includes a ""ne...",false,Likely False,None,Bruce Rauner,https://www.politifact.com/factchecks/2018/sep...,PolitiFact
38,P00039,"""Given how expansive our program already was,""...",mostly-true,Likely True,None,Chris Christie,https://www.politifact.com/factchecks/2013/nov...,PolitiFact
39,P00040,"Says a federal judge ""sanctions Tennessee ‘bir...",true,Likely True,None,Tennessee Democratic Party,https://www.politifact.com/factchecks/2012/sep...,PolitiFact
40,P00041,"On new dollar coins, ""'In God We Trust' is gone!""",false,Likely False,None,Chain email,https://www.politifact.com/factchecks/2012/sep...,PolitiFact
41,P00042,"Says ""over 1 million signatures"" were submitte...",false,Likely False,None,Democratic Party of Wisconsin,https://www.politifact.com/factchecks/2012/mar...,PolitiFact
42,P00043,"""All the billionaires in America, their net wo...",mostly-true,Likely True,None,Joe Biden,https://www.politifact.com/factchecks/2020/oct...,PolitiFact
43,P00044,African-Americans don't use drugs at a higher ...,mostly-true,Likely True,None,Van Jones,https://www.politifact.com/factchecks/2016/jul...,PolitiFact
44,P00045,"""PWNED: House GOP Dominates Twitter, YouTube, ...",true,Likely True,None,John Boehner,https://www.politifact.com/factchecks/2010/jan...,PolitiFact
45,P00046,"""This year, the federal government will have m...",half-true,Uncertain,None,John Boehner,https://www.politifact.com/factchecks/2013/oct...,PolitiFact
46,P00047,Says ex-Minneapolis officer accused of killing...,pants-fire,Likely False,None,Bloggers,https://www.politifact.com/factchecks/2020/jun...,PolitiFact
47,P00048,"""59 percent of Americans today believe that Ba...",false,Likely False,None,Arsalan Iftikhar,https://www.politifact.com/factchecks/2015/nov...,PolitiFact
48,P00049,The average age of planes in the Qatar Airways...,mostly-false,Likely False,None,Akbar Al Baker,https://www.politifact.com/factchecks/2015/may...,PolitiFact
49,P00050,Louisiana’s film incentives program is so big ...,half-true,Uncertain,None,Paul Stekler,https://www.politifact.com/factchecks/2015/feb...,PolitiFact

Since we have 162 Null rows in 'verdict_mapped' column which is a Critical column in both Model Training & Retrieval we will drop those rows as it accounts only 0.6% of the total data.

In [7]:
# Drop rows where verdict_mapped is NaN
df_merged = df_merged.dropna(subset=['verdict_mapped']).reset_index(drop=True)

# Confirm cleanup
print(f"After dropping NaN verdicts: {df_merged.shape[0]} rows remain")
print(df_merged['verdict_mapped'].value_counts(dropna=False))

After dropping NaN verdicts: 25540 rows remain
verdict_mapped
Likely False    14390
Likely True      6526
Uncertain        4624
Name: count, dtype: int64

In [8]:
# Check summary (For Verification Purpose)
print("\nNull value summary:")
print(df_merged.isnull().sum())

Null value summary:
claim_id                0
claim_text              0
verdict_original        0
verdict_mapped          0
summary             21152
originator           4388
url                  4388
dataset_source          0
dtype: int64

Since we do not have any Null values in Columns critical for Training 'claim_text', 'verdict_original' & 'verdict_mapped' we can proceed with the next steps.

In [9]:
df_merged.head(25)

,claim_id,claim_text,verdict_original,verdict_mapped,summary,originator,url,dataset_source
0,P00001,John McCain opposed bankruptcy protections for...,true,Likely True,None,Barack Obama,https://www.politifact.com/factchecks/2008/jun...,PolitiFact
1,P00002,"""Bennie Thompson actively cheer-led riots in t...",false,Likely False,None,Matt Gaetz,https://www.politifact.com/factchecks/2022/jun...,PolitiFact
2,P00003,"Says Maggie Hassan was ""out of state on 30 day...",mostly-true,Likely True,None,Kelly Ayotte,https://www.politifact.com/factchecks/2016/may...,PolitiFact
3,P00004,"""BUSTED: CDC Inflated COVID Numbers, Accused o...",false,Likely False,None,Bloggers,https://www.politifact.com/factchecks/2021/feb...,PolitiFact
4,P00005,"""I'm the only (Republican) candidate that has ...",half-true,Uncertain,None,Bobby Jindal,https://www.politifact.com/factchecks/2015/aug...,PolitiFact
5,P00006,"""There are actually only 30 countries that pra...",true,Likely True,None,S.E. Cupp,https://www.politifact.com/factchecks/2015/aug...,PolitiFact
6,P00007,"""My husband and I have never gotten a penny of...",false,Likely False,None,Michele Bachmann,https://www.politifact.com/factchecks/2011/jul...,PolitiFact
7,P00008,"""If you go strictly by the numbers, crime is d...",true,Likely True,None,George Turner,https://www.politifact.com/factchecks/2011/apr...,PolitiFact
8,P00009,"""The American people say, don't touch Social S...",mostly-true,Likely True,None,Kent Conrad,https://www.politifact.com/factchecks/2011/jan...,PolitiFact
9,P00010,"""Since 1978, CEO compensation rose over 1,000%...",true,Likely True,None,Mandela Barnes,https://www.politifact.com/factchecks/2021/jun...,PolitiFact
10,P00011,"Says her accomplishments include ""a fiscally r...",pants-fire,Likely False,None,Chris Telfer,https://www.politifact.com/factchecks/2012/mar...,PolitiFact
11,P00012,"Says President Obama’s deal ""allows Iran to pr...",false,Likely False,None,Carlos Beruff,https://www.politifact.com/factchecks/2016/may...,PolitiFact
12,P00013,"Says ""Donald Trump says climate change is a ho...",mostly-true,Likely True,None,Hillary Clinton,https://www.politifact.com/factchecks/2016/jun...,PolitiFact
13,P00014,"""At least 450,000 ballots in the key states .....",false,Likely False,None,Sidney Powell,https://www.politifact.com/factchecks/2020/nov...,PolitiFact
14,P00015,"""More than 70 percent of American adults have ...",mostly-true,Likely True,None,Stephen Carter,https://www.politifact.com/factchecks/2014/dec...,PolitiFact
15,P00016,Says the stimulus bill sent tax credits overse...,pants-fire,Likely False,None,Americans for Prosperity,https://www.politifact.com/factchecks/2012/may...,PolitiFact
16,P00017,"Tampa Bay is ""leading the state in jobs creati...",mostly-false,Likely False,None,Bob Buckhorn,https://www.politifact.com/factchecks/2015/jan...,PolitiFact
17,P00018,"Says Raphael Warnock has ""said we need to open...",mostly-false,Likely False,None,Kelly Loeffler,https://www.politifact.com/factchecks/2020/dec...,PolitiFact
18,P00019,"The IRS is going to be ""in charge"" of ""a huge ...",pants-fire,Likely False,None,Michele Bachmann,https://www.politifact.com/factchecks/2013/may...,PolitiFact
19,P00020,"""Newly discovered video shows late night deliv...",false,Likely False,None,The Gateway Pundit,https://www.politifact.com/factchecks/2021/feb...,PolitiFact
20,P00021,"Says Donald Trump ""literally has no plans to m...",mostly-true,Likely True,None,Roberta Lange,https://www.politifact.com/factchecks/2016/jun...,PolitiFact
21,P00022,"Post says a recent bill passed, and ""We get an...",pants-fire,Likely False,None,Facebook posts,https://www.politifact.com/factchecks/2021/jul...,PolitiFact
22,P00023,"With voting by mail, ""you get thousands and th...",false,Likely False,None,Donald Trump,https://www.politifact.com/factchecks/2020/apr...,PolitiFact
23,P00024,"During his governorship, Virginia made ""the la...",mostly-false,Likely False,None,Terry McAuliffe,https://www.politifact.com/factchecks/2019/mar...,PolitiFact
24,P00025,"""In the entire public school system in Camden ...",mostly-true,Likely True,None,Chris Christie,https://www.politifact.com/factchecks/2014/jan...,PolitiFact